apiVersion: v1
kind: Service
metadata:
  name: testing-api-service
spec:
  selector:
    app: testing-api
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing-api
  labels:
    app: rtesting-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testing-api
  template:
    metadata:
      labels:
        app: testing-api
    spec:
      containers:
        - name: resume
          image: scoizzle/testingapi:latest
          ports:
            - containerPort: 80